### PR TITLE
Stale element retry

### PR DESCRIPTION
**Pull request by georgecrawford**

### CODE REVIEW

**Comment by georgecrawford** [comment]
I don't know why the tests are failing - they pass for me.

**Comment by christian-bromann** [comment]
Probably because you use a wdio-sync version that isn't pulled by travis

**Comment by georgecrawford** [comment]
Ah yeah, I'll check that - thanks.

**Comment by georgecrawford** [comment]
Yep, confirmed. Perhaps you could look at https://github.com/webdriverio/wdio-sync/pull/22/files first then? :wink:

**Comment by christian-bromann** [comment]
I think we can close this since I got webdriverio/webdriverio#969 finally working.

**Pull request closed without merging**
