### PR TITLE
Change compilers to be loaded before the requires

### PR DESCRIPTION
**Pull request by snoozbuster**
This addresses #71.

### CODE REVIEW

**Comment by snoozbuster** [comment]
I can but I'm not super sure what the test would look like. (also, I don't think the test that failed is related to these changes).

**Comment by snoozbuster** [comment]
@christian-bromann added the test, can you review? (also, the test I modified doesn't pass on windows at all because the slashes go the other way. not sure how important it is to you to fix that)

**Comment by snoozbuster** [comment]
@christian-bromann any movement here?

**Comment by christian-bromann** [comment]
Couldn't merge the PR due to the line break changes. But I applied all actual changes to master. Thanks!

**Pull request closed without merging**
